---
- name: Copy application files
  copy:
    src: ../../../app/index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Restart Nginx service
  service:
    name: nginx
    state: restarted
