---
- name: Deploy Web Application
  hosts: webservers
  become: yes

  tasks:
    - name: Copy web app files to Nginx directory
      copy:
        src: ../app/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
